### ISSUE TITLE
Add 2001 Siggraph Paper to "About this Project"

### ISSUE THREAD

**Issue by pascalmueller** [josauder/procedural_city_generation#19]
Hi

Pascal Mueller from CityEngine here. Found no email, therefore via an issue.

First: cool work! 

Second: I do not know the Martin Petrasch you are referencing, but his document describes basically a re-implementation of my 2001 MSc Thesis and Siggraph Paper "Procedural Modeling of Cities" and therefore is not really a research paper. Since the stuff is so much the same thing (some of your figures are almost 1:1 to the original work), can you at least also cite the 2001 Siggraph Paper along-side of Petrasch? 
Why do I care: because I get emails from people asking me about this and complaining about it being a rip-off etc. I totally support that guys like you re-implement the stuff on their own. But it seems that the absence of correctly referencing the corresponding (quite well-known) work makes things look a bit shady to people ... Thanks for the understanding.

On another note: Looking for a job? : )

Best
Pascal

**Comment by josauder** [comment]
Hey,
of course, I will add the citation as soon as I get hold of my laptop. Sorry for the inconvenience, as we really did not look more into your paper than skimming over it, but now, comparing with with Petrasch's work, we really should have referenced you as well. Thanks but no thanks on the job offer.

Kind Regards,
Jonathan

**Comment by josauder** [comment]
Added citation with a0b5428c0c5091b07001f52430e2d658a88f51a1.
I will close this issue for now, If you have any questions/concerns feel free to post them here or mail me at jonathan_paul.sauder@dfki.de

Thanks for letting us know about this here, I'm sure there are a 100 less pleasant ways to take care of issues like this.
