### ISSUE TITLE
No module named matplotlibWidget

### ISSUE THREAD

**Issue by balzer82** [josauder/procedural_city_generation#20]
Following the "Getting to work" steps, there is a problem with missing module.

`````` python
C:\Users\Balzer\Documents\Github\procedural_city_generation>python GUI.py
Traceback (most recent call last):
  File "GUI.py", line 2, in <module>
    from window import *
  File "C:\Users\Balzer\Documents\Github\procedural_city_generation\window.py", line 176, in <module>
    from matplotlibWidget import matplotlibWidget
ImportError: No module named matplotlibWidget```

On Windows and Mac with all dependencies installed.
``````

**Comment by josauder** [comment]
Try again now. I broke the master by accident. I left a message for that in README but yeah, who reads those anyways.

Right now only the "Run" Buttons work, for configuring options run 

```
python UI.py <submodule-name> --configure <parameter-name> <new-value>
```

Or go into `inputs/<submodule-name>.json` and change the parameters yourself.
I'm hoping to add full functionality in the new UI ASAP but I don't have much time at the moment. Let me know if this fixed your mistake!
