### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by garyservin** [josauder/procedural_city_generation#23]
Hello, we're using your code as an input for another project and we plan to add some features. We would like to contribute back any changes/improvements we make and wanted to know if it is still maintained and if you will be interested in incorporating new PRs.

Thanks!

**Comment by josauder** [comment]
No, it is not actively maintained - I would be glad to incorporate new PRs.

If you have specific questions regarding the code (as not all of it is documented/tested/understandable) mail me at josaudergh@gmail.com and I will try to answer ASAP.

**Comment by garyservin** [comment]
Thank you very much!
