### ISSUE TITLE
Can Anyone help me, I got stuck at population density something to do with Singleton

### ISSUE THREAD

**Issue by kalle84** [josauder/procedural_city_generation#30]
I ran tester.py fined do error.

but when i run 
python ui.py roadmap run 

I got this error.

    population_density = population_density = np.sqrt((singleton.img2[singleton.img2.shape[0]-y*singleton.img2.shape[0]][x*singleton.img2.shape[1]][0])/255)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
(city2) PS P:\procedural_city_generation>

**Comment by julianyulu** [comment]
Hi @kalle84 , I got the same error, wondering how you solved it by the end ?  Thanks
